export type Lang = "fr" | "en";

export const CONTENT = {
  fr: {
    nav: { emplois: "Emplois", talents: "Talents locaux", pourquoi: "Pourquoi ShiftUp", cta: "Créer mon compte" },
    hero: {
      eyebrow: "L'emploi et les talents, réunis",
      headline: "Trouve un emploi\nprès de chez toi.",
      sub: "Swipe sur des offres qualifiées, réserve un talent local vérifié, ou propose tes services en freelance, le tout en 5 minutes.",
      cta1: "Je cherche un emploi →",
      cta2: "Je suis employeur →",
      stat1: { label: "Gratuit", sub: "Pour les candidats" },
      stat2: { label: "Qualifiés", sub: "Tri automatique IA" },
      stat3: { label: "5 min", sub: "Pour créer un profil" },
    },
    demo: { label: "Capture d'écran réelle", sub: "Directement tirée de l'application ShiftUp." },
    features: [
      {
        id: "emplois",
        eyebrow: "Emplois",
        title: "Swipe, comme ton application de rencontre préférée.",
        body: "Parcours des offres qualifiées en quelques secondes, sans CV interminable. Un algorithme transparent compare distance, horaires, expérience et salaire pour ne proposer que des offres pertinentes.",
        body2: "Uniquement des entreprises locales vérifiées : zéro spam, zéro faux poste.",
        img: "/shot-jobs.png",
        alt: "Capture d'écran de l'application ShiftUp, recherche d'emploi",
        accent: "violet-text",
      },
      {
        id: "talents",
        eyebrow: "Talents locaux",
        title: "Un marché de talents freelance, près de chez toi.",
        body: "Peu importe le rôle : réserve un·e photographe, créateur·rice de contenu ou expert·e marketing vérifié·e, prix transparent, aucun frais caché.",
        cta: "Je suis à mon compte →",
        img: "/shot-talents.png",
        alt: "Écran Talents locaux de l'application ShiftUp",
        accent: "leaf",
      },
      {
        id: "marketplace",
        eyebrow: "Réservation",
        title: "Découvre des talents locaux, réserve en quelques taps.",
        body: "Vidéos UGC, séances photo, contenu publicitaire. Parcours des prestations tarifées clairement et réserve directement depuis l'app.",
        img: "/shot-talents.png",
        alt: "Catalogue de talents freelance dans l'application ShiftUp",
        accent: "teal2",
      },
    ],
    ctaBanner: { title: "Prêt·e à trouver ton prochain shift ?", sub: "Crée ton profil en 5 minutes, gratuitement.", cta: "Commencer maintenant →" },
    stores: { coming: "App bientôt disponible", ios: "App Store", android: "Google Play" },
    waitlist: {
      title: "Sois parmi les premiers.",
      sub: "On lance à Montréal. Liste d'attente ouverte : travailleurs et employeurs.",
      placeholder: "ton@courriel.com",
      cta: "Rejoindre la liste →",
      sending: "Envoi…",
      tag: "Aucun spam. On te contacte avant le lancement.",
      roleWorker: "👤 Je cherche du travail",
      roleEmployer: "🏢 Je recrute",
      success: "Compte créé. Vérifie tes courriels →",
      error: "Oups, l'inscription n'a pas fonctionné. Réessaie, ou écris-nous à info@slim-ia.ca.",
      invalidEmail: "Entre une adresse courriel valide.",
      dashboard: "Votre tableau de bord →",
      demoLink: "Voir la démo →",
    },
    footer: { tagline: "Une fière conception de Slim-IA", privacy: "Confidentialité", terms: "Conditions", contact: "Nous contacter" },
  },
  en: {
    nav: { emplois: "Jobs", talents: "Local talent", pourquoi: "Why ShiftUp", cta: "Create my account" },
    hero: {
      eyebrow: "Jobs and talent, together",
      headline: "Find a job\nnear you.",
      sub: "Swipe on qualified job offers, book a verified local talent, or offer your services as a freelancer, all in 5 minutes.",
      cta1: "I'm looking for work →",
      cta2: "I'm an employer →",
      stat1: { label: "Free", sub: "For candidates" },
      stat2: { label: "Qualified", sub: "Automatic AI sorting" },
      stat3: { label: "5 min", sub: "To create a profile" },
    },
    demo: { label: "Real screenshot", sub: "Taken directly from the ShiftUp app." },
    features: [
      {
        id: "emplois",
        eyebrow: "Jobs",
        title: "Swipe, like your favorite dating app.",
        body: "Browse qualified job offers in seconds, no endless resume. A transparent algorithm compares distance, schedule, experience, and pay to only surface offers that fit.",
        body2: "Only verified local businesses: zero spam, zero fake postings.",
        img: "/shot-jobs.png",
        alt: "ShiftUp app screenshot, job search",
        accent: "violet-text",
      },
      {
        id: "talents",
        eyebrow: "Local talent",
        title: "A freelance talent marketplace, near you.",
        body: "Whatever the role: book a verified photographer, content creator, or marketing expert, transparent pricing, no hidden fees.",
        cta: "I freelance →",
        img: "/shot-talents.png",
        alt: "ShiftUp app Local talent screen",
        accent: "leaf",
      },
      {
        id: "marketplace",
        eyebrow: "Booking",
        title: "Discover local talent, book in a few taps.",
        body: "UGC videos, photo shoots, ad content. Browse clearly priced services and book directly from the app.",
        img: "/shot-talents.png",
        alt: "Freelance talent catalog in the ShiftUp app",
        accent: "teal2",
      },
    ],
    ctaBanner: { title: "Ready to find your next shift?", sub: "Create your profile in 5 minutes, for free.", cta: "Get started →" },
    stores: { coming: "App coming soon", ios: "App Store", android: "Google Play" },
    waitlist: {
      title: "Be among the first.",
      sub: "We're launching in Montréal. Waitlist open: workers and employers.",
      placeholder: "your@email.com",
      cta: "Join the waitlist →",
      sending: "Sending…",
      tag: "No spam. We'll reach out before launch.",
      roleWorker: "👤 I'm looking for work",
      roleEmployer: "🏢 I'm hiring",
      success: "Account created. Check your inbox →",
      error: "Oops, that didn't go through. Try again, or email us at info@slim-ia.ca.",
      invalidEmail: "Enter a valid email address.",
      dashboard: "Your dashboard →",
      demoLink: "See the demo →",
    },
    footer: { tagline: "A proud Slim-IA creation", privacy: "Privacy", terms: "Terms", contact: "Contact us" },
  },
} as const;

export type Content = (typeof CONTENT)[Lang];
export type Feature = Content["features"][number];
